In [5]:
import pandas as pd

In [7]:
data = pd.read_csv('fertility_Diagnosis.txt')
data

,season,age,childish diseases,accident or serious trauma,surgical intervention,high fevers in the last year,frequency of alcohol consumption,smoking habit,number of hours spent sitting per day,output
0,-0.33,0.69,0,1,1,0,0.8,0,0.88,N
1,-0.33,0.94,1,0,1,0,0.8,1,0.31,O
2,-0.33,0.50,1,0,0,0,1.0,-1,0.50,N
3,-0.33,0.75,0,1,1,0,1.0,-1,0.38,N
4,-0.33,0.67,1,1,0,0,0.8,-1,0.50,O
...,...,...,...,...,...,...,...,...,...,...
95,-1.00,0.67,1,0,0,0,1.0,-1,0.50,N
96,-1.00,0.61,1,0,0,0,0.8,0,0.50,N
97,-1.00,0.67,1,1,1,0,1.0,-1,0.31,N
98,-1.00,0.64,1,0,1,0,1.0,0,0.19,N
99,-1.00,0.69,0,1,1,0,0.6,-1,0.19,N

In [10]:
data.columns

Index(['season', 'age', 'childish diseases', 'accident or serious trauma',
       'surgical intervention', 'high fevers in the last year',
       'frequency of alcohol consumption', 'smoking habit',
       'number of hours spent sitting per day', 'output'],
      dtype='object')

In [23]:
bad = pd.read_csv('fertility.csv')

In [24]:
bad['Season'].replace({"winter":2, "spring":1, "summer":-2, "fall":-1 }, inplace= True)
bad['Childish diseases'].replace({"yes":1, "no":0}, inplace= True)
bad['Accident or serious trauma'].replace({"yes":1, "no":0}, inplace= True)
bad['Smoking habit'].replace({"daily":2, "occasional":1,"never":0}, inplace= True)
bad['Frequency of alcohol consumption'].replace({"once a weel":1,"hardly ever or never":0}, inplace= True)
bad['Surgical intervention'].replace({"yes":1,"no":0}, inplace= True)
bad.head()

,Season,Age,Childish diseases,Accident or serious trauma,Surgical intervention,High fevers in the last year,Frequency of alcohol consumption,Smoking habit,Number of hours spent sitting per day,Diagnosis
0,1,30,no,yes,yes,more than 3 months ago,once a week,occasional,16,Normal
1,1,35,yes,no,yes,more than 3 months ago,once a week,daily,6,Altered
2,1,27,yes,no,no,more than 3 months ago,hardly ever or never,never,9,Normal
3,1,32,no,yes,yes,more than 3 months ago,hardly ever or never,never,7,Normal
4,1,30,yes,yes,no,more than 3 months ago,once a week,never,9,Altered